# Generated by Django 3.0 on 2020-07-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
